### ISSUE TITLE
Partition Lost

### ISSUE THREAD

**Issue by Imprevium** [hartwork/image-bootstrap#118]
Hello Linux Newbie here,

I tried to install archlinux on my partition /dev/nvme0n1(SSD) with the following command (archpanda is the username) :

sudo image-bootstrap --hostname archpanda arch /dev/nvme0n1

I expected the program to install archlinux into the partition mentioned above, instead, it wiped my entire SSD into a linux filesystem.
I can't access windows anymore, is it possible to recover my SSD ?

Have a good day,

**Comment by hartwork** [comment]
Hi @Imprevium,

it is difficult for me to reply to your message because:
- I have empathy for the situation that you have gotten into.
- From your description, I notice that `/dev/nvme0n1` is not partition 1 but *namespace* 1; `/dev/nvme0n1p1` with suffix `n1p1` is partition 1 so it seems like `image-bootstrap` did what it was asked to do: Replace the entire disk with arch. I am aware that NVMe naming is tricky.
- While `image-bootstrap` can install to partition block devices, that mode would not work with physical hardware but only with virtual machines (..). That seems to be another important misunderstanding in usage.
- I build software with the best of intentions and pay close attention to build safe and secure software. At the same time, I am not liable for any damage that it caused. For one, because its license — the AGPL v3 or later — explicitly says so at https://www.gnu.org/licenses/agpl-3.0.en.html#section16 — but also because I cannot take risk without compensation and insurance, in general.
- Use of `sudo` is the entrance to danger zone: root permissions are a sharp knife, or even a machine gun. Use of `sudo` requires being sure and/or having a backup if things go sideways. It's easy to say in the aftermath and probably of little help, but it's true.

With that said, without backups you probably lost the first few gigabytes for sure and may be able to recover some of the original content on the parts that were not overwritten with special tools and manual expert work. I have some hope that the machine is fresh and that you lost Windows but no *personal* data of value.

If you want to discuss this incident more, I would ask to move to private communication off GitHub, e.g. e-mail, if that is okay with you. Thank you!

**Comment by Imprevium** [comment]
Updating back : Fortunately I didn't lose any personal data. Archlinux is running fine on my computer.
I'll be more careful of the command syntax in the future.

Thank you again for your quick response.

**Comment by hartwork** [comment]
Very glad to hear, thanks for the update! :pray:
