### ISSUE TITLE
Broken Python in Arch-Linux (no cloud-init possible)

### ISSUE THREAD

**Issue by kevin-olbrich** [hartwork/image-bootstrap#27]
Hi,

I just tried to run:
http://linuximages.de/openstack/arch/arch-openstack-2016-01-13-06-45-image-bootstrap-0.9.1-66-g61de370.qcow2

![arch_linux_cloud-init_failed](https://cloud.githubusercontent.com/assets/503085/12295827/10406612-ba04-11e5-8c31-df8248a421cd.png)

**Comment by hartwork** [comment]
Hi!
I noticed the same problem a day or two ago but didn't have time for a closer look. My guess would be that the cloud-init in Arch started missing a dependency on the requests module. So this could *maybe* be fixed in Arch and/or worked around in image-bootstrap.  If you investigate further yourself before I get a chance to, please post to this ticket what you find. Thanks!

**Comment by hartwork** [comment]
Looking at https://www.archlinux.org/packages/community/any/cloud-init/, package cloud-init lacks a dependency on `python2-requests` indeed. Installing that package fixes the issue. I have opened a report at https://bugs.archlinux.org/task/47741 now but upstream only shouts at me rather than taking 10 seconds to add the missing dependency, see report. So I have added a workaround to image-bootstrap now.
