### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by chris200x9** [hartwork/image-bootstrap#83]
I Downloaded an arch image from linuximges.de but I am unable to sign in, ssh connects but doesn't recognize the root password I provided my host with.

**Comment by hartwork** [comment]
The OpenStack images do not allow root log-in. You provide a public key from the outside during VM start-up and then cloud-init inside the VM sets up that key for user `arch`. That users has passwordless `sudo` enabled. If you 100% need to provide a root password you would need to run `imag-bootstrap` rather than relying on one of those images. What do you think?

**Comment by chris200x9** [comment]
Thank you for the quick reply, how would I go about providing my public key?

I put:

!#/bin/bash
echo $my_public_key > ~/.ssh/authorized_keys

as my cloud-init user data but it still doesn't work.

**Comment by hartwork** [comment]
Do you have an OpenStack environment ready? If yes, OpenStack provides the key during startup (e.g. using a config drive).

**Comment by chris200x9** [comment]
I'm trying to deploy on ramnode's new openstack cloud hosting. When I check cloud init user data I get a box to write in:

![Capture](https://user-images.githubusercontent.com/22826754/72758619-457fd380-3ba1-11ea-89d4-f6211d1f3e94.PNG)

I also have a ticket open with ramnode, I just get prompted for a password and then eventually  Permission denied (publickey,password).

**Comment by chris200x9** [comment]
I'm sorry, I just realized I can just boot froman ISO on ramnode and unstall that way. Thank you for everything.
